/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityFeed: typeof import('./src/components/admin/ActivityFeed.vue')['default']
    ApprovalTimeline: typeof import('./src/components/projects/ApprovalTimeline.vue')['default']
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    DrilldownDialog: typeof import('./src/components/admin/DrilldownDialog.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/common/ErrorState.vue')['default']
    EthicsQuestionnaire: typeof import('./src/components/projects/EthicsQuestionnaire.vue')['default']
    FilterBar: typeof import('./src/components/admin/FilterBar.vue')['default']
    LinkField: typeof import('./src/components/common/LinkField.vue')['default']
    LoadingState: typeof import('./src/components/common/LoadingState.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PendingActionsList: typeof import('./src/components/admin/PendingActionsList.vue')['default']
    PersonCard: typeof import('./src/components/projects/PersonCard.vue')['default']
    ProgrammeMatrix: typeof import('./src/components/admin/ProgrammeMatrix.vue')['default']
    ProgressLog: typeof import('./src/components/uploads/ProgressLog.vue')['default']
    ProjectActions: typeof import('./src/components/projects/ProjectActions.vue')['default']
    ProjectHeader: typeof import('./src/components/projects/ProjectHeader.vue')['default']
    ProjectListTable: typeof import('./src/components/projects/ProjectListTable.vue')['default']
    ProjectOverview: typeof import('./src/components/projects/ProjectOverview.vue')['default']
    QuestionnaireSection: typeof import('./src/components/projects/QuestionnaireSection.vue')['default']
    ReviewChannel: typeof import('./src/components/projects/ReviewChannel.vue')['default']
    RoleNav: typeof import('./src/components/navigation/RoleNav.vue')['default']
    RoleWorkloadPanel: typeof import('./src/components/admin/RoleWorkloadPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaFieldInput: typeof import('./src/components/projects/SchemaFieldInput.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
    StudentInformation: typeof import('./src/components/projects/StudentInformation.vue')['default']
    SummaryCard: typeof import('./src/components/dashboard/SummaryCard.vue')['default']
    UploadDialog: typeof import('./src/components/uploads/UploadDialog.vue')['default']
    WorkflowChart: typeof import('./src/components/dashboard/WorkflowChart.vue')['default']
    WorklistTabs: typeof import('./src/components/projects/WorklistTabs.vue')['default']
  }
}
